// SpeechScraps.swift — coco duo (k.odk)
// DICE for SPEECH: a line written at random from four roles (who is writing · what about · hurry · the close),
// taken from Mōnandæg's SPEAK room — the language follows the chosen voice.

enum SpeechScraps {
    static let table: [String: [[String]]] = [
        "en": [
            [   // 名乗り
                "I AM WRITING TO YOU IN COMPLETE CONFIDENCE",
                "PLEASE DO NOT BE SURPRISED BY THIS LETTER",
                "MY NAME WILL MEAN NOTHING TO YOU",
                "I FOUND YOUR ADDRESS THROUGH A MUTUAL FRIEND",
                "FORGIVE ME FOR ENCROACHING INTO YOUR PRIVACY",
                "I HOPE THIS MESSAGE MEETS YOU IN GOOD HEALTH",
            ],
            [   // 用件
                "A MYSTERY WANTS TO BE DISCLOSED",
                "THE MATTER IS OF MUTUAL BENEFIT",
                "YOUR PACKAGE COULD NOT BE DELIVERED",
                "A SUM IS SITTING IN AN ACCOUNT WITH NO OWNER",
                "THERE HAS BEEN UNUSUAL ACTIVITY ON YOUR LINE",
                "I HANDLE THE AFFAIRS OF A CLIENT WHO IS NO LONGER WITH US",
                "THE TRANSFER FAILED FOR REASONS BEYOND MY CONTROL",
            ],
            [   // 急かし
                "KINDLY TREAT THIS WITH THE URGENCY IT DESERVES",
                "EVERYTHING HAS BEEN ARRANGED ALREADY",
                "THE WINDOW CLOSES AT THE END OF THIS WEEK",
                "I HAVE BEEN WAITING FOR YOUR REPLY SINCE LAST WEEK",
                "NOTHING IS REQUIRED OF YOU BUT YOUR CONSENT",
                "ONLY A SMALL FEE STANDS BETWEEN US AND THE RELEASE",
            ],
            [   // 結び
                "THIS IS NOT A DREAM BUT A REALITY",
                "PLEASE KEEP THIS STRICTLY BETWEEN US",
                "I AWAIT YOUR URGENT RESPONSE",
                "THANK YOU FOR YOUR UNDERSTANDING AND COOPERATION",
                "YOURS FAITHFULLY",
            ],
        ],
        "ja": [
            [   // 名乗り
                "この度はご連絡させていただきました",
                "突然のご連絡で驚かれたことと思います",
                "私の名前をご存じないのは当然のことです",
                "共通の知人よりご住所をうかがいました",
                "私事で恐縮ですが",
                "ご健勝のこととお慶び申し上げます",
            ],
            [   // 用件
                "あなたにだけお伝えします",
                "ご不在のためお届けできませんでした",
                "持ち主のいない口座が一つ残されております",
                "お客様の回線に不審な動きがございました",
                "お互いにとって悪い話ではありません",
                "故人の資産を管理しております",
                "送金は私の力の及ばぬ理由で止まっております",
            ],
            [   // 急かし
                "至急ご確認をお願いいたします",
                "手続きはすでに完了しております",
                "期限は今週末までとなっております",
                "先週からお返事をお待ちしております",
                "お客様に必要なのはご同意のみです",
                "わずかな手数料だけが残されております",
            ],
            [   // 結び
                "これは夢ではなく、現実です",
                "くれぐれもご内密にお願いいたします",
                "ご返信を心よりお待ちしております",
                "ご理解とご協力に感謝いたします",
                "何卒よろしくお願い申し上げます",
            ],
        ],
        "de": [
            [   // 名乗り
                "ICH SCHREIBE IHNEN IN VOLLEM VERTRAUEN",
                "BITTE ENTSCHULDIGEN SIE DIE STÖRUNG",
                "MEIN NAME WIRD IHNEN NICHTS SAGEN",
                "ICH ERHIELT IHRE ADRESSE VON EINEM GEMEINSAMEN BEKANNTEN",
                "SEIEN SIE ÜBER DIESES SCHREIBEN NICHT ERSTAUNT",
            ],
            [   // 用件
                "EIN GEHEIMNIS MÖCHTE GELÜFTET WERDEN",
                "ES IST ZU UNSEREM BEIDERSEITIGEN VORTEIL",
                "IHRE SENDUNG KONNTE NICHT ZUGESTELLT WERDEN",
                "AUF EINEM KONTO LIEGT EINE SUMME OHNE EIGENTÜMER",
                "AUF IHRER LEITUNG GAB ES UNGEWÖHNLICHE BEWEGUNGEN",
                "ICH VERWALTE DEN NACHLASS EINES KLIENTEN",
            ],
            [   // 急かし
                "ALLES IST BEREITS VORBEREITET",
                "ICH WARTE SEIT LETZTER WOCHE AUF IHRE ANTWORT",
                "DIE FRIST ENDET AM FREITAG",
                "VON IHNEN WIRD NICHTS VERLANGT ALS IHR EINVERSTÄNDNIS",
                "BEHANDELN SIE DIES BITTE MIT DER GEBOTENEN EILE",
            ],
            [   // 結び
                "DIES IST KEIN TRAUM, SONDERN WIRKLICHKEIT",
                "BITTE BEWAHREN SIE STILLSCHWEIGEN",
                "ICH ERWARTE IHRE DRINGENDE ANTWORT",
                "ICH DANKE IHNEN FÜR IHR VERSTÄNDNIS",
                "MIT VORZÜGLICHER HOCHACHTUNG",
            ],
        ],
        "fr": [
            [   // 名乗り
                "JE VOUS ÉCRIS EN TOUTE CONFIANCE",
                "PARDONNEZ CETTE INTRUSION DANS VOTRE VIE",
                "MON NOM NE VOUS DIRA RIEN",
                "J AI OBTENU VOTRE ADRESSE PAR UNE CONNAISSANCE COMMUNE",
                "NE SOYEZ PAS SURPRIS PAR CETTE LETTRE",
            ],
            [   // 用件
                "UN MYSTÈRE DEMANDE À ÊTRE RÉVÉLÉ",
                "CELA EST DANS NOTRE INTÉRÊT COMMUN",
                "VOTRE COLIS N A PAS PU ÊTRE LIVRÉ",
                "UNE SOMME DORT SUR UN COMPTE SANS PROPRIÉTAIRE",
                "DES MOUVEMENTS INHABITUELS ONT ÉTÉ CONSTATÉS SUR VOTRE LIGNE",
                "JE GÈRE LES AFFAIRES D UN CLIENT QUI N EST PLUS",
            ],
            [   // 急かし
                "TOUT A DÉJÀ ÉTÉ ARRANGÉ",
                "J ATTENDS VOTRE RÉPONSE DEPUIS LA SEMAINE DERNIÈRE",
                "LE DÉLAI EXPIRE VENDREDI",
                "ON NE VOUS DEMANDE RIEN D AUTRE QUE VOTRE ACCORD",
                "VEUILLEZ TRAITER CECI AVEC L URGENCE QU IL MÉRITE",
            ],
            [   // 結び
                "CE N EST PAS UN RÊVE MAIS LA RÉALITÉ",
                "GARDEZ CECI STRICTEMENT ENTRE NOUS",
                "DANS L ATTENTE DE VOTRE RÉPONSE URGENTE",
                "MERCI DE VOTRE COMPRÉHENSION",
                "VEUILLEZ AGRÉER MES SALUTATIONS DISTINGUÉES",
            ],
        ],
        "es": [
            [   // 名乗り
                "LE ESCRIBO CON TODA CONFIANZA",
                "DISCULPE LA INTROMISIÓN EN SU PRIVACIDAD",
                "MI NOMBRE NO LE DIRÁ NADA",
                "OBTUVE SU DIRECCIÓN POR UN CONOCIDO COMÚN",
                "NO SE SORPRENDA POR ESTA CARTA",
            ],
            [   // 用件
                "UN MISTERIO QUIERE SER REVELADO",
                "ES UN ASUNTO DE BENEFICIO MUTUO",
                "SU PAQUETE NO PUDO SER ENTREGADO",
                "HAY UNA SUMA EN UNA CUENTA SIN DUEÑO",
                "SE HAN DETECTADO MOVIMIENTOS INUSUALES EN SU LÍNEA",
                "ADMINISTRO LOS BIENES DE UN CLIENTE QUE YA NO ESTÁ",
            ],
            [   // 急かし
                "TODO ESTÁ YA PREPARADO",
                "ESPERO SU RESPUESTA DESDE LA SEMANA PASADA",
                "EL PLAZO TERMINA EL VIERNES",
                "NO SE LE PIDE NADA MÁS QUE SU CONSENTIMIENTO",
                "LE RUEGO ATIENDA ESTO CON LA DEBIDA URGENCIA",
            ],
            [   // 結び
                "ESTO NO ES UN SUEÑO SINO LA REALIDAD",
                "LE RUEGO ABSOLUTA DISCRECIÓN",
                "QUEDO A LA ESPERA DE SU PRONTA RESPUESTA",
                "GRACIAS POR SU COMPRENSIÓN",
                "ATENTAMENTE",
            ],
        ],
        "it": [
            [   // 名乗り
                "LE SCRIVO IN PIENA RISERVATEZZA",
                "MI SCUSO PER L INTRUSIONE",
                "IL MIO NOME NON LE DIRÀ NULLA",
                "HO AVUTO IL SUO INDIRIZZO DA UN CONOSCENTE COMUNE",
                "NON SI STUPISCA DI QUESTA LETTERA",
            ],
            [   // 用件
                "UN MISTERO CHIEDE DI ESSERE SVELATO",
                "È UNA QUESTIONE DI RECIPROCO VANTAGGIO",
                "IL SUO PACCO NON È STATO CONSEGNATO",
                "SU UN CONTO GIACE UNA SOMMA SENZA PROPRIETARIO",
                "SONO STATI RILEVATI MOVIMENTI INSOLITI SULLA SUA LINEA",
                "CURO GLI AFFARI DI UN CLIENTE CHE NON C È PIÙ",
            ],
            [   // 急かし
                "È GIÀ TUTTO PREDISPOSTO",
                "ATTENDO UNA SUA RISPOSTA DALLA SCORSA SETTIMANA",
                "IL TERMINE SCADE VENERDÌ",
                "NON LE SI CHIEDE ALTRO CHE IL SUO CONSENSO",
                "LA PREGO DI TRATTARE LA COSA CON URGENZA",
            ],
            [   // 結び
                "QUESTO NON È UN SOGNO MA LA REALTÀ",
                "LA PREGO DELLA MASSIMA RISERVATEZZA",
                "RESTO IN ATTESA DI UN SUO URGENTE RISCONTRO",
                "GRAZIE PER LA COMPRENSIONE",
                "DISTINTI SALUTI",
            ],
        ],
        "zh": [
            [   // 名乗り
                "我怀着完全的信任写信给您",
                "打扰您的生活，十分抱歉",
                "我的名字对您毫无意义",
                "您的地址是一位共同的朋友告知的",
                "请不要为这封信感到意外",
            ],
            [   // 用件
                "有一个秘密想要被揭开",
                "这对我们双方都有好处",
                "您的包裹无法投递",
                "有一笔款项留在一个无人认领的账户里",
                "您的线路上出现了异常的活动",
                "我负责处理一位已故客户的事务",
            ],
            [   // 急かし
                "一切都已经安排妥当",
                "我从上周起就在等您的回复",
                "期限将于本周五截止",
                "您只需表示同意，别无他求",
                "请以应有的紧迫处理此事",
            ],
            [   // 結び
                "这不是梦，而是现实",
                "请务必对此保密",
                "静候您的紧急回复",
                "感谢您的理解与配合",
                "此致敬礼",
            ],
        ],
        "ko": [
            [   // 名乗り
                "전적인 신뢰로 이 글을 씁니다",
                "사생활을 방해하여 죄송합니다",
                "제 이름은 당신에게 아무 의미가 없을 것입니다",
                "공통의 지인을 통해 주소를 알게 되었습니다",
                "이 편지에 놀라지 마시기 바랍니다",
            ],
            [   // 用件
                "밝혀지기를 기다리는 비밀이 있습니다",
                "서로에게 이로운 일입니다",
                "귀하의 소포를 배달하지 못했습니다",
                "주인 없는 계좌에 한 금액이 남아 있습니다",
                "귀하의 회선에서 비정상적인 움직임이 발견되었습니다",
                "이미 세상을 떠난 고객의 재산을 관리하고 있습니다",
            ],
            [   // 急かし
                "모든 준비는 이미 끝났습니다",
                "지난주부터 답장을 기다리고 있습니다",
                "기한은 이번 주 금요일까지입니다",
                "귀하께 필요한 것은 동의뿐입니다",
                "부디 시급한 사안으로 처리해 주십시오",
            ],
            [   // 結び
                "이것은 꿈이 아니라 현실입니다",
                "부디 비밀로 해 주십시오",
                "빠른 회신을 기다리겠습니다",
                "이해와 협조에 감사드립니다",
                "그럼 이만 줄입니다",
            ],
        ],
        "pt": [
            [   // 名乗り
                "ESCREVO-LHE COM TODA A CONFIANÇA",
                "PERDOE A INTROMISSÃO NA SUA VIDA",
                "O MEU NOME NADA LHE DIRÁ",
                "OBTIVE A SUA MORADA POR UM CONHECIDO COMUM",
                "NÃO SE ADMIRE COM ESTA CARTA",
            ],
            [   // 用件
                "UM MISTÉRIO QUER SER REVELADO",
                "É UM ASSUNTO DE BENEFÍCIO MÚTUO",
                "A SUA ENCOMENDA NÃO PÔDE SER ENTREGUE",
                "EXISTE UMA QUANTIA NUMA CONTA SEM DONO",
                "FORAM DETECTADOS MOVIMENTOS INVULGARES NA SUA LINHA",
                "TRATO DOS BENS DE UM CLIENTE QUE JÁ PARTIU",
            ],
            [   // 急かし
                "ESTÁ TUDO JÁ PREPARADO",
                "AGUARDO A SUA RESPOSTA DESDE A SEMANA PASSADA",
                "O PRAZO TERMINA NA SEXTA-FEIRA",
                "NADA LHE É PEDIDO ALÉM DO SEU CONSENTIMENTO",
                "PEÇO QUE TRATE DISTO COM A DEVIDA URGÊNCIA",
            ],
            [   // 結び
                "ISTO NÃO É UM SONHO, MAS A REALIDADE",
                "PEÇO-LHE ABSOLUTA DISCRIÇÃO",
                "FICO A AGUARDAR RESPOSTA URGENTE",
                "OBRIGADO PELA SUA COMPREENSÃO",
                "COM OS MELHORES CUMPRIMENTOS",
            ],
        ],
        "nl": [
            [   // 名乗り
                "IK SCHRIJF U IN VOL VERTROUWEN",
                "EXCUSEER DE INBREUK OP UW PRIVACY",
                "MIJN NAAM ZAL U NIETS ZEGGEN",
                "IK KREEG UW ADRES VIA EEN GEMEENSCHAPPELIJKE KENNIS",
                "VERBAAS U NIET OVER DEZE BRIEF",
            ],
            [   // 用件
                "EEN GEHEIM WIL ONTHULD WORDEN",
                "HET IS IN ONS WEDERZIJDS BELANG",
                "UW PAKKET KON NIET BEZORGD WORDEN",
                "OP EEN REKENING STAAT EEN BEDRAG ZONDER EIGENAAR",
                "ER IS ONGEBRUIKELIJKE ACTIVITEIT OP UW LIJN",
                "IK BEHEER DE NALATENSCHAP VAN EEN CLIËNT",
            ],
            [   // 急かし
                "ALLES IS REEDS GEREGELD",
                "IK WACHT SINDS VORIGE WEEK OP UW ANTWOORD",
                "DE TERMIJN VERLOOPT VRIJDAG",
                "ER WORDT NIETS VAN U GEVRAAGD DAN UW TOESTEMMING",
                "BEHANDELT U DIT MET DE NODIGE SPOED",
            ],
            [   // 結び
                "DIT IS GEEN DROOM MAAR WERKELIJKHEID",
                "BEWAART U ALSTUBLIEFT STILZWIJGEN",
                "IN AFWACHTING VAN UW SPOEDIGE ANTWOORD",
                "DANK VOOR UW BEGRIP",
                "MET DE MEESTE HOOGACHTING",
            ],
        ],
        "ru": [
            [   // 名乗り
                "Я ПИШУ ВАМ С ПОЛНЫМ ДОВЕРИЕМ",
                "ПРОСТИТЕ ЗА ВТОРЖЕНИЕ В ВАШУ ЖИЗНЬ",
                "МОЁ ИМЯ НИЧЕГО ВАМ НЕ СКАЖЕТ",
                "ВАШ АДРЕС МНЕ ДАЛ ОБЩИЙ ЗНАКОМЫЙ",
                "НЕ УДИВЛЯЙТЕСЬ ЭТОМУ ПИСЬМУ",
            ],
            [   // 用件
                "ТАЙНА ЖДЁТ, ЧТОБЫ ЕЁ РАСКРЫЛИ",
                "ЭТО В НАШИХ ОБЩИХ ИНТЕРЕСАХ",
                "ВАША ПОСЫЛКА НЕ БЫЛА ДОСТАВЛЕНА",
                "НА СЧЕТУ ЛЕЖИТ СУММА БЕЗ ВЛАДЕЛЬЦА",
                "НА ВАШЕЙ ЛИНИИ ЗАМЕЧЕНА НЕОБЫЧНАЯ АКТИВНОСТЬ",
                "Я ВЕДУ ДЕЛА КЛИЕНТА, КОТОРОГО БОЛЬШЕ НЕТ",
            ],
            [   // 急かし
                "ВСЁ УЖЕ ПОДГОТОВЛЕНО",
                "Я ЖДУ ВАШЕГО ОТВЕТА С ПРОШЛОЙ НЕДЕЛИ",
                "СРОК ИСТЕКАЕТ В ПЯТНИЦУ",
                "ОТ ВАС НЕ ТРЕБУЕТСЯ НИЧЕГО, КРОМЕ СОГЛАСИЯ",
                "ПРОШУ ОТНЕСТИСЬ К ЭТОМУ СО ВСЕЙ СРОЧНОСТЬЮ",
            ],
            [   // 結び
                "ЭТО НЕ СОН, А РЕАЛЬНОСТЬ",
                "ПРОШУ СОХРАНИТЬ ЭТО В ТАЙНЕ",
                "ЖДУ ВАШЕГО СРОЧНОГО ОТВЕТА",
                "БЛАГОДАРЮ ЗА ПОНИМАНИЕ",
                "С ГЛУБОКИМ УВАЖЕНИЕМ",
            ],
        ],
        "sv": [
            [   // 名乗り
                "JAG SKRIVER TILL ER I FULLT FÖRTROENDE",
                "FÖRLÅT INTRÅNGET I ERT PRIVATLIV",
                "MITT NAMN SÄGER ER INGENTING",
                "JAG FICK ER ADRESS AV EN GEMENSAM BEKANT",
                "BLI INTE FÖRVÅNAD ÖVER DETTA BREV",
            ],
            [   // 用件
                "EN HEMLIGHET VILL BLI AVSLÖJAD",
                "DET ÄR TILL VÅR ÖMSESIDIGA NYTTA",
                "ERT PAKET KUNDE INTE LEVERERAS",
                "PÅ ETT KONTO LIGGER EN SUMMA UTAN ÄGARE",
                "OVANLIG AKTIVITET HAR NOTERATS PÅ ER LINJE",
                "JAG SKÖTER EN AVLIDEN KLIENTS AFFÄRER",
            ],
            [   // 急かし
                "ALLT ÄR REDAN ORDNAT",
                "JAG HAR VÄNTAT PÅ ERT SVAR SEDAN FÖRRA VECKAN",
                "FRISTEN GÅR UT PÅ FREDAG",
                "INGET KRÄVS AV ER UTOM ERT SAMTYCKE",
                "BEHANDLA DETTA MED DEN BRÅDSKA DET FÖRTJÄNAR",
            ],
            [   // 結び
                "DETTA ÄR INGEN DRÖM UTAN VERKLIGHET",
                "JAG BER ER OM FULLSTÄNDIG DISKRETION",
                "JAG AVVAKTAR ERT SKYNDSAMMA SVAR",
                "TACK FÖR ER FÖRSTÅELSE",
                "MED VÄNLIG HÄLSNING",
            ],
        ],
        "da": [
            [   // 名乗り
                "JEG SKRIVER TIL DEM I FULD FORTROLIGHED",
                "UNDSKYLD FORSTYRRELSEN I DERES LIV",
                "MIT NAVN SIGER DEM INTET",
                "JEG FIK DERES ADRESSE AF EN FÆLLES BEKENDT",
                "BLIV IKKE OVERRASKET OVER DETTE BREV",
            ],
            [   // 用件
                "EN HEMMELIGHED VIL AFSLØRES",
                "DET ER TIL FÆLLES FORDEL",
                "DERES PAKKE KUNNE IKKE LEVERES",
                "PÅ EN KONTO STÅR ET BELØB UDEN EJER",
                "DER ER SET USÆDVANLIG AKTIVITET PÅ DERES LINJE",
                "JEG VARETAGER EN AFDØD KLIENTS SAGER",
            ],
            [   // 急かし
                "ALT ER ALLEREDE ORDNET",
                "JEG HAR VENTET PÅ DERES SVAR SIDEN SIDSTE UGE",
                "FRISTEN UDLØBER PÅ FREDAG",
                "DER KRÆVES INTET AF DEM UD OVER DERES SAMTYKKE",
                "BEHANDL DETTE MED DEN HAST DET FORTJENER",
            ],
            [   // 結び
                "DETTE ER INGEN DRØM, MEN VIRKELIGHED",
                "JEG BEDER OM FULD DISKRETION",
                "JEG AFVENTER DERES HURTIGE SVAR",
                "TAK FOR DERES FORSTÅELSE",
                "MED VENLIG HILSEN",
            ],
        ],
        "nb": [
            [   // 名乗り
                "JEG SKRIVER TIL DEM I FULL FORTROLIGHET",
                "BEKLAGER FORSTYRRELSEN I DERES LIV",
                "MITT NAVN SIER DEM INGENTING",
                "JEG FIKK ADRESSEN DERES AV EN FELLES KJENT",
                "BLI IKKE OVERRASKET OVER DETTE BREVET",
            ],
            [   // 用件
                "EN HEMMELIGHET VIL BLI AVSLØRT",
                "DET ER TIL GJENSIDIG NYTTE",
                "PAKKEN DERES KUNNE IKKE LEVERES",
                "PÅ EN KONTO STÅR ET BELØP UTEN EIER",
                "DET ER REGISTRERT UVANLIG AKTIVITET PÅ LINJEN DERES",
                "JEG FORVALTER EN AVDØD KLIENTS SAKER",
            ],
            [   // 急かし
                "ALT ER ALLEREDE ORDNET",
                "JEG HAR VENTET PÅ SVAR SIDEN FORRIGE UKE",
                "FRISTEN GÅR UT PÅ FREDAG",
                "DET KREVES INGENTING AV DEM UTOVER SAMTYKKE",
                "BEHANDLE DETTE MED DEN HAST DET FORTJENER",
            ],
            [   // 結び
                "DETTE ER INGEN DRØM, MEN VIRKELIGHET",
                "JEG BER OM FULL DISKRESJON",
                "JEG AVVENTER DERES RASKE SVAR",
                "TAKK FOR FORSTÅELSEN",
                "MED VENNLIG HILSEN",
            ],
        ],
        "fi": [
            [   // 名乗り
                "KIRJOITAN TEILLE TÄYDESSÄ LUOTTAMUKSESSA",
                "ANTEEKSI HÄIRIÖ YKSITYISYYTEENNE",
                "NIMENI EI SANO TEILLE MITÄÄN",
                "SAIN OSOITTEENNE YHTEISELTÄ TUTULTA",
                "ÄLKÄÄ HÄMMÄSTYKÖ TÄSTÄ KIRJEESTÄ",
            ],
            [   // 用件
                "SALAISUUS HALUAA TULLA PALJASTETUKSI",
                "TÄMÄ ON MOLEMPIEN ETU",
                "PAKETTIANNE EI VOITU TOIMITTAA",
                "TILILLÄ ON SUMMA JOLLA EI OLE OMISTAJAA",
                "LINJALLANNE ON HAVAITTU EPÄTAVALLISTA LIIKENNETTÄ",
                "HOIDAN EDESMENNEEN ASIAKKAAN ASIOITA",
            ],
            [   // 急かし
                "KAIKKI ON JO JÄRJESTETTY",
                "OLEN ODOTTANUT VASTAUSTANNE VIIME VIIKOSTA",
                "MÄÄRÄAIKA PÄÄTTYY PERJANTAINA",
                "TEILTÄ EI VAADITA MUUTA KUIN SUOSTUMUS",
                "PYYDÄN KÄSITTELEMÄÄN TÄMÄN KIIREELLISENÄ",
            ],
            [   // 結び
                "TÄMÄ EI OLE UNTA VAAN TODELLISUUTTA",
                "PYYDÄN TÄYDELLISTÄ VAITIOLOA",
                "ODOTAN PIKAISTA VASTAUSTANNE",
                "KIITOS YMMÄRRYKSESTÄNNE",
                "YSTÄVÄLLISIN TERVEISIN",
            ],
        ],
        "pl": [
            [   // 名乗り
                "PISZĘ DO PANA W PEŁNYM ZAUFANIU",
                "PRZEPRASZAM ZA NARUSZENIE PRYWATNOŚCI",
                "MOJE NAZWISKO NIC PANU NIE POWIE",
                "PANA ADRES OTRZYMAŁEM OD WSPÓLNEGO ZNAJOMEGO",
                "PROSZĘ SIĘ NIE DZIWIĆ TEMU LISTOWI",
            ],
            [   // 用件
                "TAJEMNICA CHCE ZOSTAĆ UJAWNIONA",
                "TO JEST W NASZYM WSPÓLNYM INTERESIE",
                "PANA PRZESYŁKA NIE MOGŁA ZOSTAĆ DORĘCZONA",
                "NA KONCIE LEŻY KWOTA BEZ WŁAŚCICIELA",
                "NA PANA LINII ODNOTOWANO NIETYPOWY RUCH",
                "PROWADZĘ SPRAWY KLIENTA, KTÓREGO JUŻ NIE MA",
            ],
            [   // 急かし
                "WSZYSTKO ZOSTAŁO JUŻ PRZYGOTOWANE",
                "CZEKAM NA ODPOWIEDŹ OD ZESZŁEGO TYGODNIA",
                "TERMIN UPŁYWA W PIĄTEK",
                "NIE WYMAGA SIĘ NICZEGO POZA PANA ZGODĄ",
                "PROSZĘ POTRAKTOWAĆ TO PILNIE",
            ],
            [   // 結び
                "TO NIE SEN, LECZ RZECZYWISTOŚĆ",
                "PROSZĘ O PEŁNĄ DYSKRECJĘ",
                "OCZEKUJĘ PILNEJ ODPOWIEDZI",
                "DZIĘKUJĘ ZA ZROZUMIENIE",
                "Z WYRAZAMI SZACUNKU",
            ],
        ],
        "cs": [
            [   // 名乗り
                "PÍŠI VÁM S NAPROSTOU DŮVĚROU",
                "OMLOUVÁM SE ZA NARUŠENÍ SOUKROMÍ",
                "MÉ JMÉNO VÁM NIC NEŘEKNE",
                "VAŠI ADRESU MI DAL SPOLEČNÝ ZNÁMÝ",
                "NEDIVTE SE TOMUTO DOPISU",
            ],
            [   // 用件
                "TAJEMSTVÍ CHCE BÝT ODHALENO",
                "JE TO V NAŠEM SPOLEČNÉM ZÁJMU",
                "VAŠI ZÁSILKU NEBYLO MOŽNÉ DORUČIT",
                "NA ÚČTU LEŽÍ ČÁSTKA BEZ MAJITELE",
                "NA VAŠÍ LINCE BYL ZAZNAMENÁN NEOBVYKLÝ POHYB",
                "VEDU ZÁLEŽITOSTI KLIENTA, KTERÝ JIŽ NENÍ MEZI NÁMI",
            ],
            [   // 急かし
                "VŠE JE JIŽ PŘIPRAVENO",
                "ČEKÁM NA VAŠI ODPOVĚĎ OD MINULÉHO TÝDNE",
                "LHŮTA VYPRŠÍ V PÁTEK",
                "NEŽÁDÁ SE PO VÁS NIC NEŽ SOUHLAS",
                "ŽÁDÁM VÁS O NEODKLADNÉ VYŘÍZENÍ",
            ],
            [   // 結び
                "TOTO NENÍ SEN, ALE SKUTEČNOST",
                "ŽÁDÁM VÁS O NAPROSTOU MLČENLIVOST",
                "OČEKÁVÁM VAŠI NALÉHAVOU ODPOVĚĎ",
                "DĚKUJI ZA POCHOPENÍ",
                "S ÚCTOU",
            ],
        ],
        "sk": [
            [   // 名乗り
                "PÍŠEM VÁM S ÚPLNOU DÔVEROU",
                "OSPRAVEDLŇUJEM SA ZA NARUŠENIE SÚKROMIA",
                "MOJE MENO VÁM NIČ NEPOVIE",
                "VAŠU ADRESU MI DAL SPOLOČNÝ ZNÁMY",
                "NEČUDUJTE SA TOMUTO LISTU",
            ],
            [   // 用件
                "TAJOMSTVO CHCE BYŤ ODHALENÉ",
                "JE TO V NAŠOM SPOLOČNOM ZÁUJME",
                "VAŠU ZÁSIELKU NEBOLO MOŽNÉ DORUČIŤ",
                "NA ÚČTE LEŽÍ SUMA BEZ MAJITEĽA",
                "NA VAŠEJ LINKE BOL ZAZNAMENANÝ NEZVYČAJNÝ POHYB",
                "VEDIEM ZÁLEŽITOSTI KLIENTA, KTORÝ UŽ NIE JE MEDZI NAMI",
            ],
            [   // 急かし
                "VŠETKO JE UŽ PRIPRAVENÉ",
                "ČAKÁM NA VAŠU ODPOVEĎ OD MINULÉHO TÝŽDŇA",
                "LEHOTA UPLYNIE V PIATOK",
                "NEŽIADA SA OD VÁS NIČ OKREM SÚHLASU",
                "ŽIADAM VÁS O BEZODKLADNÉ VYBAVENIE",
            ],
            [   // 結び
                "TOTO NIE JE SEN, ALE SKUTOČNOSŤ",
                "PROSÍM O ÚPLNÚ DISKRÉTNOSŤ",
                "OČAKÁVAM VAŠU NALIEHAVÚ ODPOVEĎ",
                "ĎAKUJEM ZA POCHOPENIE",
                "S ÚCTOU",
            ],
        ],
        "tr": [
            [   // 名乗り
                "SİZE TAM BİR GÜVENLE YAZIYORUM",
                "ÖZEL HAYATINIZA MÜDAHALE İÇİN ÖZÜR DİLERİM",
                "ADIM SİZE BİR ŞEY İFADE ETMEYECEK",
                "ADRESİNİZİ ORTAK BİR TANIDIKTAN ALDIM",
                "BU MEKTUBA ŞAŞIRMAYIN",
            ],
            [   // 用件
                "BİR SIR AÇIĞA ÇIKMAK İSTİYOR",
                "BU KARŞILIKLI YARARIMIZADIR",
                "KARGONUZ TESLİM EDİLEMEDİ",
                "SAHİBİ OLMAYAN BİR HESAPTA BİR MEBLAĞ DURUYOR",
                "HATTINIZDA OLAĞAN DIŞI HAREKET SAPTANDI",
                "VEFAT ETMİŞ BİR MÜVEKKİLİN İŞLERİNİ YÜRÜTÜYORUM",
            ],
            [   // 急かし
                "HER ŞEY ÇOKTAN HAZIRLANDI",
                "GEÇEN HAFTADAN BERİ YANITINIZI BEKLİYORUM",
                "SÜRE CUMA GÜNÜ DOLUYOR",
                "SİZDEN ONAYINIZDAN BAŞKA BİR ŞEY İSTENMİYOR",
                "LÜTFEN BUNU İVEDİLİKLE ELE ALIN",
            ],
            [   // 結び
                "BU BİR RÜYA DEĞİL, GERÇEKTİR",
                "LÜTFEN BUNU TAMAMEN GİZLİ TUTUN",
                "ACİL YANITINIZI BEKLİYORUM",
                "ANLAYIŞINIZ İÇİN TEŞEKKÜR EDERİM",
                "SAYGILARIMLA",
            ],
        ],
        "el": [
            [   // 名乗り
                "ΣΑΣ ΓΡΑΦΩ ΜΕ ΑΠΟΛΥΤΗ ΕΜΠΙΣΤΟΣΥΝΗ",
                "ΣΥΓΓΝΩΜΗ ΓΙΑ ΤΗΝ ΕΝΟΧΛΗΣΗ",
                "ΤΟ ΟΝΟΜΑ ΜΟΥ ΔΕΝ ΘΑ ΣΑΣ ΠΕΙ ΤΙΠΟΤΑ",
                "ΠΗΡΑ ΤΗ ΔΙΕΥΘΥΝΣΗ ΣΑΣ ΑΠΟ ΚΟΙΝΟ ΓΝΩΣΤΟ",
                "ΜΗΝ ΕΚΠΛΑΓΕΙΤΕ ΑΠΟ ΑΥΤΟ ΤΟ ΓΡΑΜΜΑ",
            ],
            [   // 用件
                "ΕΝΑ ΜΥΣΤΙΚΟ ΘΕΛΕΙ ΝΑ ΑΠΟΚΑΛΥΦΘΕΙ",
                "ΕΙΝΑΙ ΠΡΟΣ ΑΜΟΙΒΑΙΟ ΟΦΕΛΟΣ",
                "ΤΟ ΔΕΜΑ ΣΑΣ ΔΕΝ ΠΑΡΑΔΟΘΗΚΕ",
                "ΣΕ ΕΝΑΝ ΛΟΓΑΡΙΑΣΜΟ ΥΠΑΡΧΕΙ ΠΟΣΟ ΧΩΡΙΣ ΚΑΤΟΧΟ",
                "ΕΝΤΟΠΙΣΤΗΚΕ ΑΣΥΝΗΘΙΣΤΗ ΚΙΝΗΣΗ ΣΤΗ ΓΡΑΜΜΗ ΣΑΣ",
                "ΔΙΑΧΕΙΡΙΖΟΜΑΙ ΤΙΣ ΥΠΟΘΕΣΕΙΣ ΕΝΟΣ ΕΚΛΙΠΟΝΤΟΣ ΠΕΛΑΤΗ",
            ],
            [   // 急かし
                "ΟΛΑ ΕΧΟΥΝ ΗΔΗ ΚΑΝΟΝΙΣΤΕΙ",
                "ΠΕΡΙΜΕΝΩ ΑΠΑΝΤΗΣΗ ΑΠΟ ΤΗΝ ΠΕΡΑΣΜΕΝΗ ΕΒΔΟΜΑΔΑ",
                "Η ΠΡΟΘΕΣΜΙΑ ΛΗΓΕΙ ΤΗΝ ΠΑΡΑΣΚΕΥΗ",
                "ΔΕΝ ΖΗΤΕΙΤΑΙ ΤΙΠΟΤΑ ΠΕΡΑ ΑΠΟ ΤΗ ΣΥΓΚΑΤΑΘΕΣΗ ΣΑΣ",
                "ΠΑΡΑΚΑΛΩ ΑΝΤΙΜΕΤΩΠΙΣΤΕ ΤΟ ΕΠΕΙΓΟΝΤΩΣ",
            ],
            [   // 結び
                "ΑΥΤΟ ΔΕΝ ΕΙΝΑΙ ΟΝΕΙΡΟ ΑΛΛΑ ΠΡΑΓΜΑΤΙΚΟΤΗΤΑ",
                "ΠΑΡΑΚΑΛΩ ΓΙΑ ΑΠΟΛΥΤΗ ΕΧΕΜΥΘΕΙΑ",
                "ΑΝΑΜΕΝΩ ΕΠΕΙΓΟΥΣΑ ΑΠΑΝΤΗΣΗ",
                "ΕΥΧΑΡΙΣΤΩ ΓΙΑ ΤΗΝ ΚΑΤΑΝΟΗΣΗ",
                "ΜΕ ΕΚΤΙΜΗΣΗ",
            ],
        ],
        "hu": [
            [   // 名乗り
                "TELJES BIZALOMMAL ÍROK ÖNNEK",
                "ELNÉZÉST A MAGÁNÉLETÉBE VALÓ BEAVATKOZÁSÉRT",
                "A NEVEM SEMMIT SEM MOND ÖNNEK",
                "A CÍMÉT EGY KÖZÖS ISMERŐSTŐL KAPTAM",
                "NE LEPŐDJÖN MEG EZEN A LEVÉLEN",
            ],
            [   // 用件
                "EGY TITOK FEL AKAR TÁRULNI",
                "EZ KÖLCSÖNÖSEN ELŐNYÖS",
                "A CSOMAGJÁT NEM LEHETETT KÉZBESÍTENI",
                "EGY SZÁMLÁN GAZDÁTLAN ÖSSZEG HEVER",
                "SZOKATLAN MOZGÁST ÉSZLELTÜNK A VONALÁN",
                "EGY ELHUNYT ÜGYFÉL ÜGYEIT INTÉZEM",
            ],
            [   // 急かし
                "MINDEN ELŐ VAN KÉSZÍTVE",
                "A MÚLT HÉT ÓTA VÁROM A VÁLASZÁT",
                "A HATÁRIDŐ PÉNTEKEN JÁR LE",
                "ÖNTŐL SEMMI MÁST NEM KÉRÜNK, CSAK A BELEEGYEZÉSÉT",
                "KÉREM, KEZELJE SÜRGŐSEN",
            ],
            [   // 結び
                "EZ NEM ÁLOM, HANEM VALÓSÁG",
                "KÉREM A TELJES TITOKTARTÁST",
                "SÜRGŐS VÁLASZÁT VÁROM",
                "KÖSZÖNÖM A MEGÉRTÉSÉT",
                "TISZTELETTEL",
            ],
        ],
        "ro": [
            [   // 名乗り
                "VĂ SCRIU CU DEPLINĂ ÎNCREDERE",
                "IERTAȚI INTRUZIUNEA ÎN VIAȚA DUMNEAVOASTRĂ",
                "NUMELE MEU NU VĂ VA SPUNE NIMIC",
                "AM PRIMIT ADRESA DUMNEAVOASTRĂ DE LA O CUNOȘTINȚĂ COMUNĂ",
                "NU VĂ MIRAȚI DE ACEASTĂ SCRISOARE",
            ],
            [   // 用件
                "UN MISTER VREA SĂ FIE DEZVĂLUIT",
                "ESTE ÎN INTERESUL NOSTRU COMUN",
                "COLETUL DUMNEAVOASTRĂ NU A PUTUT FI LIVRAT",
                "ÎNTR-UN CONT ZACE O SUMĂ FĂRĂ PROPRIETAR",
                "S-A CONSTATAT O ACTIVITATE NEOBIȘNUITĂ PE LINIA DUMNEAVOASTRĂ",
                "MĂ OCUP DE AFACERILE UNUI CLIENT CARE NU MAI ESTE",
            ],
            [   // 急かし
                "TOTUL A FOST DEJA PREGĂTIT",
                "AȘTEPT RĂSPUNSUL DUMNEAVOASTRĂ DE SĂPTĂMÂNA TRECUTĂ",
                "TERMENUL EXPIRĂ VINERI",
                "NU VI SE CERE NIMIC ÎN AFARĂ DE ACORDUL DUMNEAVOASTRĂ",
                "VĂ ROG SĂ TRATAȚI ACEASTA CU URGENȚĂ",
            ],
            [   // 結び
                "ACESTA NU ESTE UN VIS, CI REALITATEA",
                "VĂ ROG SĂ PĂSTRAȚI DISCREȚIA DEPLINĂ",
                "AȘTEPT UN RĂSPUNS URGENT",
                "VĂ MULȚUMESC PENTRU ÎNȚELEGERE",
                "CU STIMĂ",
            ],
        ],
        "uk": [
            [   // 名乗り
                "Я ПИШУ ВАМ З ПОВНОЮ ДОВІРОЮ",
                "ПЕРЕПРОШУЮ ЗА ВТРУЧАННЯ У ВАШЕ ЖИТТЯ",
                "МОЄ ІМЯ ВАМ НІЧОГО НЕ СКАЖЕ",
                "ВАШУ АДРЕСУ МЕНІ ДАВ СПІЛЬНИЙ ЗНАЙОМИЙ",
                "НЕ ДИВУЙТЕСЯ ЦЬОМУ ЛИСТУ",
            ],
            [   // 用件
                "ТАЄМНИЦЯ ЧЕКАЄ НА РОЗКРИТТЯ",
                "ЦЕ У НАШИХ СПІЛЬНИХ ІНТЕРЕСАХ",
                "ВАША ПОСИЛКА НЕ БУЛА ДОСТАВЛЕНА",
                "НА РАХУНКУ ЛЕЖИТЬ СУМА БЕЗ ВЛАСНИКА",
                "НА ВАШІЙ ЛІНІЇ ПОМІЧЕНО НЕЗВИЧНУ АКТИВНІСТЬ",
                "Я ВЕДУ СПРАВИ КЛІЄНТА, ЯКОГО БІЛЬШЕ НЕМАЄ",
            ],
            [   // 急かし
                "УСЕ ВЖЕ ПІДГОТОВЛЕНО",
                "Я ЧЕКАЮ НА ВАШУ ВІДПОВІДЬ ІЗ МИНУЛОГО ТИЖНЯ",
                "ТЕРМІН СПЛИВАЄ У ПЯТНИЦЮ",
                "ВІД ВАС НЕ ПОТРІБНО НІЧОГО, КРІМ ЗГОДИ",
                "ПРОШУ ПОСТАВИТИСЯ ДО ЦЬОГО ТЕРМІНОВО",
            ],
            [   // 結び
                "ЦЕ НЕ СОН, А РЕАЛЬНІСТЬ",
                "ПРОШУ ЗБЕРЕГТИ ЦЕ У ТАЄМНИЦІ",
                "ЧЕКАЮ НА ТЕРМІНОВУ ВІДПОВІДЬ",
                "ДЯКУЮ ЗА РОЗУМІННЯ",
                "З ПОВАГОЮ",
            ],
        ],
        "he": [
            [   // 名乗り
                "אני כותב אליך באמון מלא",
                "סליחה על ההפרעה לפרטיותך",
                "שמי לא יאמר לך דבר",
                "קיבלתי את כתובתך ממכר משותף",
                "אל תופתע ממכתב זה",
            ],
            [   // 用件
                "סוד מבקש להיחשף",
                "זה לתועלת שנינו",
                "החבילה שלך לא נמסרה",
                "בחשבון מונח סכום ללא בעלים",
                "נרשמה פעילות חריגה בקו שלך",
                "אני מטפל בענייניו של לקוח שאיננו עוד",
            ],
            [   // 急かし
                "הכול כבר הוסדר",
                "אני ממתין לתשובתך מאז השבוע שעבר",
                "המועד האחרון הוא ביום שישי",
                "לא נדרש ממך דבר מלבד הסכמתך",
                "אנא טפל בכך בדחיפות",
            ],
            [   // 結び
                "זה אינו חלום אלא מציאות",
                "אנא שמור על סודיות מלאה",
                "אני ממתין לתשובתך הדחופה",
                "תודה על הבנתך",
                "בכבוד רב",
            ],
        ],
        "ar": [
            [   // 名乗り
                "أكتب إليك بكل ثقة",
                "أعتذر عن اقتحام خصوصيتك",
                "اسمي لن يعني لك شيئا",
                "حصلت على عنوانك من معرفة مشتركة",
                "لا تستغرب هذه الرسالة",
            ],
            [   // 用件
                "هناك سر يريد أن ينكشف",
                "الأمر فيه منفعة متبادلة",
                "لم يتم تسليم طردك",
                "هناك مبلغ في حساب بلا صاحب",
                "رصدنا نشاطا غير معتاد على خطك",
                "أتولى شؤون عميل لم يعد بيننا",
            ],
            [   // 急かし
                "كل شيء أعد سلفا",
                "أنتظر ردك منذ الأسبوع الماضي",
                "تنتهي المهلة يوم الجمعة",
                "لا يطلب منك سوى موافقتك",
                "أرجو التعامل مع الأمر بما يستحقه من عجلة",
            ],
            [   // 結び
                "هذا ليس حلما بل حقيقة",
                "أرجو الحفاظ على السرية التامة",
                "أنتظر ردك العاجل",
                "شكرا لتفهمك",
                "مع خالص التقدير",
            ],
        ],
        "hi": [
            [   // 名乗り
                "मैं आपको पूर्ण विश्वास के साथ लिख रहा हूँ",
                "आपकी निजता में दखल के लिए क्षमा करें",
                "मेरा नाम आपके लिए कुछ नहीं कहेगा",
                "आपका पता एक साझा परिचित से मिला",
                "इस पत्र से आश्चर्यचकित न हों",
            ],
            [   // 用件
                "एक रहस्य प्रकट होना चाहता है",
                "यह हम दोनों के हित में है",
                "आपका पार्सल वितरित नहीं किया जा सका",
                "एक खाते में बिना मालिक की राशि पड़ी है",
                "आपकी लाइन पर असामान्य गतिविधि देखी गई है",
                "मैं एक दिवंगत ग्राहक के मामले देखता हूँ",
            ],
            [   // 急かし
                "सब कुछ पहले से तैयार है",
                "मैं पिछले सप्ताह से आपके उत्तर की प्रतीक्षा कर रहा हूँ",
                "समय सीमा शुक्रवार को समाप्त होती है",
                "आपसे केवल आपकी सहमति चाहिए",
                "कृपया इसे तत्काल देखें",
            ],
            [   // 結び
                "यह सपना नहीं, वास्तविकता है",
                "कृपया इसे पूर्णतः गोपनीय रखें",
                "मैं आपके शीघ्र उत्तर की प्रतीक्षा करता हूँ",
                "आपकी समझ के लिए धन्यवाद",
                "सादर",
            ],
        ],
        "th": [
            [   // 名乗り
                "ผมเขียนถึงคุณด้วยความไว้วางใจอย่างเต็มที่",
                "ขออภัยที่รบกวนความเป็นส่วนตัวของคุณ",
                "ชื่อของผมคงไม่มีความหมายกับคุณ",
                "ผมได้ที่อยู่ของคุณจากคนรู้จักร่วมกัน",
                "อย่าแปลกใจกับจดหมายฉบับนี้",
            ],
            [   // 用件
                "มีความลับที่รอการเปิดเผย",
                "เรื่องนี้เป็นประโยชน์ต่อเราทั้งสองฝ่าย",
                "พัสดุของคุณไม่สามารถจัดส่งได้",
                "มีเงินจำนวนหนึ่งค้างอยู่ในบัญชีที่ไม่มีเจ้าของ",
                "พบความเคลื่อนไหวผิดปกติในสายของคุณ",
                "ผมดูแลกิจการของลูกค้าที่ล่วงลับไปแล้ว",
            ],
            [   // 急かし
                "ทุกอย่างได้จัดเตรียมไว้เรียบร้อยแล้ว",
                "ผมรอคำตอบของคุณตั้งแต่สัปดาห์ที่แล้ว",
                "กำหนดเวลาสิ้นสุดในวันศุกร์",
                "ไม่ต้องการสิ่งใดจากคุณนอกจากความยินยอม",
                "กรุณาดำเนินการโดยด่วน",
            ],
            [   // 結び
                "นี่ไม่ใช่ความฝัน แต่เป็นความจริง",
                "กรุณาเก็บเรื่องนี้เป็นความลับ",
                "ผมรอคำตอบด่วนจากคุณ",
                "ขอบคุณสำหรับความเข้าใจ",
                "ด้วยความนับถือ",
            ],
        ],
        "id": [
            [   // 名乗り
                "SAYA MENULIS KEPADA ANDA DENGAN PENUH KEPERCAYAAN",
                "MAAF ATAS GANGGUAN PADA PRIVASI ANDA",
                "NAMA SAYA TIDAK AKAN BERARTI APA-APA BAGI ANDA",
                "SAYA MEMPEROLEH ALAMAT ANDA DARI KENALAN BERSAMA",
                "JANGAN TERKEJUT DENGAN SURAT INI",
            ],
            [   // 用件
                "SEBUAH RAHASIA INGIN TERUNGKAP",
                "INI DEMI KEUNTUNGAN KITA BERSAMA",
                "PAKET ANDA TIDAK DAPAT DIANTARKAN",
                "ADA SEJUMLAH UANG DI REKENING TANPA PEMILIK",
                "TERDETEKSI AKTIVITAS TIDAK LAZIM PADA JALUR ANDA",
                "SAYA MENGURUS URUSAN KLIEN YANG TELAH TIADA",
            ],
            [   // 急かし
                "SEMUANYA SUDAH DIATUR",
                "SAYA MENUNGGU BALASAN ANDA SEJAK MINGGU LALU",
                "BATAS WAKTUNYA HARI JUMAT",
                "TIDAK ADA YANG DIMINTA DARI ANDA SELAIN PERSETUJUAN",
                "MOHON DITANGANI DENGAN SEGERA",
            ],
            [   // 結び
                "INI BUKAN MIMPI MELAINKAN KENYATAAN",
                "MOHON JAGA KERAHASIAAN SEPENUHNYA",
                "SAYA MENANTIKAN JAWABAN SEGERA",
                "TERIMA KASIH ATAS PENGERTIAN ANDA",
                "HORMAT SAYA",
            ],
        ],
        "vi": [
            [   // 名乗り
                "TÔI VIẾT CHO BẠN VỚI TẤT CẢ LÒNG TIN",
                "XIN LỖI VÌ ĐÃ LÀM PHIỀN ĐỜI TƯ CỦA BẠN",
                "TÊN TÔI SẼ CHẲNG NÓI LÊN ĐIỀU GÌ VỚI BẠN",
                "TÔI CÓ ĐỊA CHỈ CỦA BẠN QUA MỘT NGƯỜI QUEN CHUNG",
                "XIN ĐỪNG NGẠC NHIÊN VỀ LÁ THƯ NÀY",
            ],
            [   // 用件
                "MỘT BÍ MẬT MUỐN ĐƯỢC HÉ LỘ",
                "ĐIỀU NÀY CÓ LỢI CHO CẢ HAI CHÚNG TA",
                "BƯU KIỆN CỦA BẠN KHÔNG THỂ ĐƯỢC GIAO",
                "CÓ MỘT KHOẢN TIỀN NẰM TRONG TÀI KHOẢN KHÔNG CHỦ",
                "ĐÃ GHI NHẬN HOẠT ĐỘNG BẤT THƯỜNG TRÊN ĐƯỜNG DÂY CỦA BẠN",
                "TÔI LO LIỆU VIỆC CỦA MỘT THÂN CHỦ ĐÃ QUA ĐỜI",
            ],
            [   // 急かし
                "MỌI THỨ ĐÃ ĐƯỢC CHUẨN BỊ SẴN",
                "TÔI ĐÃ CHỜ HỒI ÂM CỦA BẠN TỪ TUẦN TRƯỚC",
                "THỜI HẠN KẾT THÚC VÀO THỨ SÁU",
                "KHÔNG ĐÒI HỎI GÌ Ở BẠN NGOÀI SỰ ĐỒNG Ý",
                "XIN HÃY XỬ LÝ KHẨN TRƯƠNG",
            ],
            [   // 結び
                "ĐÂY KHÔNG PHẢI GIẤC MƠ MÀ LÀ SỰ THẬT",
                "XIN HÃY GIỮ KÍN HOÀN TOÀN",
                "TÔI CHỜ HỒI ÂM KHẨN CỦA BẠN",
                "CẢM ƠN SỰ THÔNG CẢM CỦA BẠN",
                "TRÂN TRỌNG",
            ],
        ],
    ]

    /// a new line: two or three roles most of the time, kept in their order
    static func line(language: String) -> String {
        let tag = String(language.prefix(2))
        let pool = table[tag] ?? table["en"] ?? []
        guard !pool.isEmpty else { return "" }
        let want = min(pool.count, [1, 2, 2, 2, 3, 3, 3, 4, 4].randomElement() ?? 2)
        let roles = (0..<pool.count).shuffled().prefix(want).sorted()
        let parts = roles.compactMap { pool[$0].randomElement() }
        let tight = tag == "ja" || tag == "zh"
        return parts.joined(separator: tight ? "。" : " ")
    }
}
